import type { SegmentConfig } from '$lib/types';

export const segmentConfigs: SegmentConfig[] = [
  {
    id: 'title',
    width: 1920,
    height: 1080,
    component: 'TitleSegment',
    label: 'Agentic AI for Interactive Media Creation',
  },
  {
    id: 'skills',
    width: 1920,
    height: 1080,
    component: 'SkillsSegment',
    label: 'A broad skills landscape',
  },
  {
    id: 'llm-prediction',
    width: 1920,
    height: 4200,
    component: 'LLMPredictionSegment',
    label: 'What is an LLM?',
  },
  {
    id: 'agentic-chat',
    width: 1920,
    height: 7700,
    component: 'AgenticChatSegment',
    label: 'From chatbot to agent',
    // Static fallbacks; the segment registers precise runtime rects.
    zoomTargets: [
      { id: 'thinking-one', xOffset: 550, yOffset: 900, width: 820, height: 260 },
      { id: 'python-run', xOffset: 550, yOffset: 1200, width: 820, height: 360 },
      { id: 'python-fix', xOffset: 550, yOffset: 1600, width: 820, height: 360 },
      { id: 'python-validation', xOffset: 550, yOffset: 2000, width: 820, height: 360 },
      { id: 'thinking-two', xOffset: 550, yOffset: 3200, width: 820, height: 220 },
      { id: 'search-results', xOffset: 550, yOffset: 3500, width: 820, height: 560 },
      { id: 'source-excerpt', xOffset: 550, yOffset: 4050, width: 820, height: 220 },
    ],
  },
  {
    id: 'context',
    width: 1920,
    height: 6400,
    component: 'ContextSegment',
    label: 'From prompt to context',
  },
  {
    id: 'context-engineering',
    width: 1920,
    height: 5200,
    component: 'ContextEngineeringSegment',
    label: 'From prompt engineering to context engineering',
  },
  {
    id: 'tokens',
    width: 1920,
    height: 3600,
    component: 'TokensSegment',
    label: 'Tokens, and how much fits',
  },
  {
    id: 'granularity',
    width: 1920,
    height: 3800,
    component: 'GranularitySegment',
    label: 'A spectrum, not a switch',
  },
  {
    id: 'uses-design',
    width: 1920,
    height: 3800,
    component: 'UsesDesignSegment',
    label: 'If you design',
  },
  {
    id: 'uses-technical',
    width: 1920,
    height: 5400,
    component: 'UsesTechnicalSegment',
    label: 'If you build',
  },
  {
    id: 'care-overview',
    width: 1920,
    height: 1080,
    component: 'CareOverviewSegment',
    label: 'Where care is required',
  },
  {
    id: 'care-wrong',
    width: 1920,
    height: 4800,
    component: 'CareWrongSegment',
    label: 'Confidently wrong',
  },
  {
    id: 'care-agreement',
    width: 1920,
    height: 4800,
    component: 'CareAgreementSegment',
    label: 'The agreement trap',
  },
  {
    id: 'care-visual-gap',
    width: 1920,
    height: 4800,
    component: 'CareVisualGapSegment',
    label: 'The visual gap',
  },
  {
    id: 'care-training',
    width: 1920,
    height: 5400,
    component: 'CareTrainingSegment',
    label: 'What went in',
  },
  {
    id: 'care-ownership',
    width: 1920,
    height: 4600,
    component: 'CareOwnershipSegment',
    label: 'Who owns this?',
  },
  {
    id: 'care-context',
    width: 1920,
    height: 5800,
    component: 'CareContextSegment',
    label: 'What you put in',
  },
  {
    id: 'care-attribution',
    width: 1920,
    height: 5600,
    component: 'CareAttributionSegment',
    label: 'Name your collaborators',
  },
  {
    id: 'care-audit',
    width: 1920,
    height: 1080,
    component: 'CareAuditSegment',
    label: 'The audit, live',
  },
  {
    id: 'care-numbers',
    width: 1920,
    height: 6000,
    component: 'CareNumbersSegment',
    label: 'The audit, quantified',
  },
  {
    id: 'care-footprint',
    width: 1920,
    height: 6200,
    component: 'CareFootprintSegment',
    label: 'One cheeseburger. Is that the whole story?',
  },
  {
    id: 'key-learnings',
    width: 1920,
    height: 5200,
    component: 'KeyLearningsSegment',
    label: 'Key takeaways',
  },
  {
    id: 'resources',
    width: 1920,
    height: 3200,
    component: 'ResourcesSegment',
    label: 'Useful resources',
  },
];
